services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: "localhost"
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
        gitlab_rails['initial_root_password'] = 'CHANGEME123'
    ports:
      - "80:80"
      - "8822:22"
    volumes:
      - ./gitlab/data/docker/gitlab/etc/gitlab:/etc/gitlab
      - ./gitlab/data/docker/gitlab/var/opt/gitlab:/var/opt/gitlab
      - ./gitlab/data/docker/gitlab/var/log/gitlab:/var/log/gitlab
    networks:
      - gitlab_net

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: unless-stopped
    privileged: true
    volumes:
      - ./gitlab/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab_net

networks:
  gitlab_net:
    name: gitlab_net

